### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by kxs156** [jean-bovet/BTrain#15]
Hi, trying to compile your program and get this error:

_kasparstromme@xxxxxx btrain % swiftc btrainapp.swift
btrainapp.swift:15:1: error: 'main' attribute cannot be used in a module that contains top-level code
@main
^
btrainapp.swift:1:1: note: top-level code defined in this source file
// Copyright 2021-22 Jean Bovet
^
btrainapp.swift:22:13: error: cannot find 'LayoutDocument' in scope
            LayoutDocument(layout: Layout(uuid: "new-layout"))
            ^~~~~~~~~~~~~~
btrainapp.swift:22:36: error: cannot find 'Layout' in scope
            LayoutDocument(layout: Layout(uuid: "new-layout"))
                                   ^~~~~~
btrainapp.swift:24:13: error: cannot find 'DocumentView' in scope
            DocumentView(document: configuration.document, layout: configuration.document.layout)
            ^~~~~~~~~~~~
kasparstromme@xxxxxx btrain %_ 

Any tips? I am not too familiar with coding so maybe I am doing something very wrong also :) But I have a CS 2 and would like to see what I can do with your software. Best Kaspar

**Comment by jean-bovet** [comment]
Hi!

I would recommend opening the project `BTrain.xcodeproj` (double-click on it should open Xcode if you have Xcode installed; otherwise, you can install it directly from the Mac App Store). After opening it in Xcode, you can build and run it using Command-R. Let me know how it goes. I don't have a CS2, so I would be curious to see what works with it!

**Comment by kxs156** [comment]
Ok, trying with Xcode but crashing on this:

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/102526068/161022075-37fb9784-2e52-4536-9baf-bdf9adce7e71.png">

**Comment by jean-bovet** [comment]
Interesting. What macOS version are you using? What Xcode version are you using?

**Comment by kxs156** [comment]
11.6.2 and 13.2.1

**Comment by jean-bovet** [comment]
Ah, it looks like you need macOS 12.x version to work as some features of SwiftUI are only implemented in 12.x. Let me update the README file with that information.
