### ISSUE TITLE
Binary release

### ISSUE THREAD

**Issue by fbaube** [jean-bovet/BTrain#29]
XCode is not really intended for non-technical Mac users. Also it occupies a vast amount of disk space. I would imagine that many potential BTrain enthusiasts do not have it installed. 

Would it be possible to make a binary release ?

**Comment by jean-bovet** [comment]
Yes, this is a good idea, let me see what I can do!

**Comment by jean-bovet** [comment]
Done - you can now find the binary for version 1.5 [here](https://github.com/jean-bovet/BTrain/releases/tag/1.5).

**Comment by fbaube** [comment]
I'm running Monterey (macos 12.6.3) and got this error from 1.5:

```
> open /Applications/BTrain.app/
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10825 "kLSIncompatibleSystemVersionErr: The app cannot run on the current OS version" UserInfo={_LSLine=3863, _LSFunction=_LSOpenStuffCallLocal}
```

I've never seen this message before, from any Mac app.

Would it help if I provided some kind of debugging info ?

**Comment by jean-bovet** [comment]
Ah, you need to be on Ventura (13.x). Let me see if I can re-compile for 12.x, it will depend on the number of APIs that are not available for 12.x.

**Comment by fbaube** [comment]
My own Mac is not capable of running Ventura, so it is not an option. 

"About This Mac" says "MacBook Pro (Retina, 13-inch, Early 2015)".

**Comment by jean-bovet** [comment]
Ah, sorry to hear that! Unfortunately, I don't have the resources at the moment to make my code compatible with OS version before Ventura.
